# Use admin/pass as user/password credentials to login to openemr (from OE_USER and OE_PASS below)
# MYSQL_HOST and MYSQL_ROOT_PASS are required for openemr
# MYSQL_USER, MYSQL_PASS, OE_USER, MYSQL_PASS are optional for openemr and
#   if not provided, then default to openemr, openemr, admin, and pass respectively.
version: '3.8'
  
networks:
  db:
  proxy_default:
    external: true

services:
  mysql:
    container_name: mysql
    restart: always
    image: mariadb:10.11
    command: ['mysqld','--character-set-server=utf8mb4']
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD:  
      MYSQL_DATABASE: ${SITE_PATH}
      MYSQL_USER: ${SITE_PATH}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    networks:
      - db  
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  openemr:
    restart: always
    container_name: openemr
    #image: openemr/openemr:7.0.1
    image: openemr/openemr:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.services.${SITE_PATH}.loadbalancer.server.port=80
      - traefik.http.routers.${SITE_PATH}.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.${SITE_PATH}.rule=Host(`${DOMAIN_NAME}`)
    networks:
      - db
      - proxy_default
    volumes:
    - log-data:/var/log
    - site-data:/var/www/localhost/htdocs/openemr/sites
    - ignored:/etc/ssl
    - ignored:/etc/letsencrypt
    environment:
      TZ: ${TZ}
      DOMAIN_NAME:
      SITE_PATH:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${SITE_PATH}
      MYSQL_USER: ${SITE_PATH}
      MYSQL_PASS: 
      OE_USER: 
      OE_PASS: 
    depends_on:
      mysql:
        condition: service_healthy
    
volumes:
   ignored: # traefik
   log-data:
      driver_opts:
            type: none
            device: ${VOL_LOG}
            o: bind
   site-data:
      driver_opts:
            type: none
            device: ${VOL_SITE}
            o: bind
   db-data:
      driver_opts:
            type: none
            device: ${VOL_DB}
            o: bind
